export const reportEntries = [
  {
    reportId: "REP010",
    date: "Apr 12, 2023",
    fullName: "Chinedu Okafor",
    queryType: "Failed Transaction",
    assignedTo: "Amina Mohammed",
    status: "Resolved",
    lastUpdated: "Apr 12, 2023 | 09:32AM",
    resolutionTime: "2 hours",
  },
  {
    reportId: "REP009",
    date: "Apr 12, 2023",
    fullName: "Amina Mohammed",
    queryType: "KYC Verification Issue",
    assignedTo: "Segun Adebayo",
    status: "In-progress",
    lastUpdated: "Apr 12, 2023 | 09:32AM",
    resolutionTime: "-",
  },
  {
    reportId: "REP008",
    date: "Apr 12, 2023",
    fullName: "Tunde Adetokunbo",
    queryType: "Virtual Card Activation",
    assignedTo: "Ngozi Uche",
    status: "Assigned",
    lastUpdated: "Apr 12, 2023 | 09:32AM",
    resolutionTime: "-",
  },
  {
    reportId: "REP007",
    date: "Apr 12, 2023",
    fullName: "Funke Adeyemi",
    queryType: "Account Suspension Appeal",
    assignedTo: "Bisi Olamide",
    status: "Resolved",
    lastUpdated: "Apr 12, 2023 | 09:32AM",
    resolutionTime: "3 days",
  },
  {
    reportId: "REP006",
    date: "Apr 12, 2023",
    fullName: "Chika Nwosu",
    queryType: "Unauthorized Transaction",
    assignedTo: "Ibrahim Musa",
    status: "Resolved",
    lastUpdated: "Apr 12, 2023 | 09:32AM",
    resolutionTime: "1-week",
  },
  {
    reportId: "REP005",
    date: "Apr 12, 2023",
    fullName: "Bisi Olamide",
    queryType: "Login Issues",
    assignedTo: "Kemi Adekunle",
    status: "In-progress",
    lastUpdated: "Apr 12, 2023 | 09:32AM",
    resolutionTime: "-",
  },
  {
    reportId: "REP004",
    date: "Apr 12, 2023",
    fullName: "Segun Adebayo",
    queryType: "Account Balance Discrepancy",
    assignedTo: "Chinedu Okafor",
    status: "Resolved",
    lastUpdated: "Apr 12, 2023 | 09:32AM",
    resolutionTime: "1-week",
  },
  {
    reportId: "REP003",
    date: "Apr 12, 2023",
    fullName: "Ngozi Uche",
    queryType: "Currency Exchange Rate",
    assignedTo: "Amina Mohammed",
    status: "Assigned",
    lastUpdated: "Apr 12, 2023 | 09:32AM",
    resolutionTime: "-",
  },
  {
    reportId: "REP002",
    date: "Apr 12, 2023",
    fullName: "Ibrahim Musa",
    queryType: "Change of Address",
    assignedTo: "Ibrahim Musa",
    status: "Resolved",
    lastUpdated: "Apr 12, 2023 | 09:32AM",
    resolutionTime: "3 days",
  },
  {
    reportId: "REP001",
    date: "Apr 12, 2023",
    fullName: "Kemi Adekunle",
    queryType: "Account Closure Request",
    assignedTo: "Segun Adebayo",
    status: "Assigned",
    lastUpdated: "Apr 12, 2023 | 09:32AM",
    resolutionTime: "-",
  },
  {
    reportId: "REP003",
    date: "Apr 12, 2023",
    fullName: "Ngozi Uche",
    queryType: "Currency Exchange Rate",
    assignedTo: "Amina Mohammed",
    status: "Assigned",
    lastUpdated: "Apr 12, 2023 | 09:32AM",
    resolutionTime: "-",
  },
  {
    reportId: "REP002",
    date: "Apr 12, 2023",
    fullName: "Ibrahim Musa",
    queryType: "Change of Address",
    assignedTo: "Ibrahim Musa",
    status: "Resolved",
    lastUpdated: "Apr 12, 2023 | 09:32AM",
    resolutionTime: "3 days",
  },
  {
    reportId: "REP001",
    date: "Apr 12, 2023",
    fullName: "Kemi Adekunle",
    queryType: "Account Closure Request",
    assignedTo: "Segun Adebayo",
    status: "Assigned",
    lastUpdated: "Apr 12, 2023 | 09:32AM",
    resolutionTime: "-",
  },
];
