export const serviceEntries = [
  {
    id: "1",
    apiName: "Get User Details",
    endpoint: "/api/v1/users/{user_id}",
    method: "GET",
    lastAccessed: "2024-08-21",
    description: "Retrieves detailed user information",
    status: "Active",
  },
  {
    id: "2",
    apiName: "Update User Info",
    endpoint: "/api/v1/users/{user_id}/update",
    method: "PUT",
    lastAccessed: "2024-08-20",
    description: "Updates user profile data",
    status: "Inactive",
  },
  {
    id: "3",
    apiName: "User Transactions",
    endpoint: "/api/v1/users/{user_id}/transactions",
    method: "GET",
    lastAccessed: "2024-08-18",
    description: "Fetches user's recent transactions",
    status: "Active",
  },
  {
    id: "4",
    apiName: "Create Transaction",
    endpoint: "/api/v1/transactions/create",
    method: "POST",
    lastAccessed: "2024-08-20",
    description: "Initiates a new transaction",
    status: "Active",
  },
  {
    id: "5",
    apiName: "Delete User",
    endpoint: "/api/v1/users/{user_id}/delete",
    method: "DELETE",
    lastAccessed: "2024-08-20",
    description: "Deletes a user account",
    status: "Active",
  },
  {
    id: "6",
    apiName: "Reset Password",
    endpoint: "/api/v1/users/{user_id}/reset-password",
    method: "POST",
    lastAccessed: "2024-08-20",
    description: "Resets user password",
    status: "Active",
  },
  {
    id: "7",
    apiName: "Get User Activity",
    endpoint: "/api/v1/users/{user_id}/activity",
    method: "GET",
    lastAccessed: "2024-08-20",
    description: "Retrieves user's activity log",
    status: "Active",
  },
  {
    id: "8",
    apiName: "Suspend User",
    endpoint: "/api/v1/users/{user_id}/suspend",
    method: "POST",
    lastAccessed: "2024-08-20",
    description: "Suspends the user account",
    status: "Inactive",
  },
  {
    id: "9",
    apiName: "Verify User",
    endpoint: "/api/v1/users/{user_id}/verify",
    method: "POST",
    lastAccessed: "2024-08-20",
    description: "Verifies the user's account",
    status: "Active",
  },
  {
    id: "10",
    apiName: "List User API Keys",
    endpoint: "/api/v1/users/{user_id}/api-keys",
    method: "GET",
    lastAccessed: "2024-08-20",
    description: "Lists all API keys for the user",
    status: "Active",
  },
  {
    id: "11",
    apiName: "List User API Keys",
    endpoint: "/api/v1/users/{user_id}/api-keys",
    method: "GET",
    lastAccessed: "2024-08-20",
    description: "Lists all API keys for the user",
    status: "Active",
  },
  {
    id: "12",
    apiName: "List User API Keys",
    endpoint: "/api/v1/users/{user_id}/api-keys",
    method: "GET",
    lastAccessed: "2024-08-20",
    description: "Lists all API keys for the user",
    status: "Active",
  },
];
