interface Transaction {
  id: string;
  accountNumber: string;
  bank: string;
  date: string;
  time: string;
  arrowType: string;
  paymentType: string;
  currency: string;
  paymentMethod: string;
  status: string;
  amount: string;
}
export const transactions: Transaction[] = [
  {
    id: "TXN010",
    accountNumber: "1234567890",
    date: "Apr 12, 2023",
    time: "09:32AM",
    bank: "Kuda Bank",
    paymentType: "Credit",
    currency: "NGN",
    paymentMethod: "Transfer",
    status: "Successful",
    amount: "₦200,000.00",
    arrowType: "down", // For arrow indication
  },
  {
    id: "TXN009",
    accountNumber: "9876543210",
    date: "Apr 12, 2023",
    time: "09:32AM",
    bank: "GTBank",
    paymentType: "Credit",
    currency: "NGN",
    paymentMethod: "Transfer",
    status: "Pending",
    amount: "₦120,000.00",
    arrowType: "down",
  },
  {
    id: "TXN008",
    accountNumber: "1234567890",
    date: "Apr 12, 2023",
    time: "09:32AM",
    bank: "Bridgecard (Bank)",
    paymentType: "Debit",
    currency: "USD",
    paymentMethod: "Debit Card",
    status: "Successful",
    amount: "$150,000.00",
    arrowType: "up",
  },
  {
    id: "TXN011",
    accountNumber: "1234567890",
    date: "Apr 12, 2023",
    time: "09:32AM",
    bank: "Kuda Bank",
    paymentType: "Credit",
    currency: "NGN",
    paymentMethod: "Transfer",
    status: "Successful",
    amount: "₦200,000.00",
    arrowType: "down", // For arrow indication
  },
  {
    id: "TXN0012",
    accountNumber: "9876543210",
    date: "Apr 12, 2023",
    time: "09:32AM",
    bank: "GTBank",
    paymentType: "Credit",
    currency: "NGN",
    paymentMethod: "Transfer",
    status: "Pending",
    amount: "₦120,000.00",
    arrowType: "down",
  },
  {
    id: "TXN0013",
    accountNumber: "1234567890",
    date: "Apr 12, 2023",
    time: "09:32AM",
    bank: "Bridgecard (Bank)",
    paymentType: "Debit",
    currency: "USD",
    paymentMethod: "Debit Card",
    status: "Successful",
    amount: "$150,000.00",
    arrowType: "up",
  },
  {
    id: "TXN014",
    accountNumber: "1234567890",
    date: "Apr 12, 2023",
    time: "09:32AM",
    bank: "Kuda Bank",
    paymentType: "Credit",
    currency: "NGN",
    paymentMethod: "Transfer",
    status: "Successful",
    amount: "₦200,000.00",
    arrowType: "down", // For arrow indication
  },
  {
    id: "TXN015",
    accountNumber: "9876543210",
    date: "Apr 12, 2023",
    time: "09:32AM",
    bank: "GTBank",
    paymentType: "Credit",
    currency: "NGN",
    paymentMethod: "Transfer",
    status: "Pending",
    amount: "₦120,000.00",
    arrowType: "down",
  },
  {
    id: "TXN016",
    accountNumber: "1234567890",
    date: "Apr 12, 2023",
    time: "09:32AM",
    bank: "Bridgecard (Bank)",
    paymentType: "Debit",
    currency: "USD",
    paymentMethod: "Debit Card",
    status: "Successful",
    amount: "$150,000.00",
    arrowType: "up",
  },
  {
    id: "TXN017",
    accountNumber: "1234567890",
    date: "Apr 12, 2023",
    time: "09:32AM",
    bank: "Kuda Bank",
    paymentType: "Credit",
    currency: "NGN",
    paymentMethod: "Transfer",
    status: "Successful",
    amount: "₦200,000.00",
    arrowType: "down", // For arrow indication
  },
  {
    id: "TXN018",
    accountNumber: "9876543210",
    date: "Apr 12, 2023",
    time: "09:32AM",
    bank: "GTBank",
    paymentType: "Credit",
    currency: "NGN",
    paymentMethod: "Transfer",
    status: "Pending",
    amount: "₦120,000.00",
    arrowType: "down",
  },
  {
    id: "TXN019",
    accountNumber: "1234567890",
    date: "Apr 12, 2023",
    time: "09:32AM",
    bank: "Bridgecard (Bank)",
    paymentType: "Debit",
    currency: "USD",
    paymentMethod: "Debit Card",
    status: "Successful",
    amount: "$150,000.00",
    arrowType: "up",
  },
];
